version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=c9
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=c9bot
    volumes:
      - ./etc/database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql:ro
      - /mysql_data:/var/lib/mysql
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_ADDRESS=db:3306
      - DATABASE_USERNAME=c9
      - DATABASE_PASSWORD=$DB_PASSWORD
      - DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
    depends_on:
      - db
